In [ ]:
# 1: Pide al usuario ingresar una lista de números y luego imprime la suma de esos números.

print("SUMA")

number1 = int(input("Ingrese el primer número: "))
number2 = int(input("Ingrese el segundo número: "))

suma = number1 + number2

print("La suma de es: ", suma ,", gracias.")

In [10]:
# 2: Solicita al usuario ingresar una lista de números y calcula el producto de esos números.

print("MULTIPLICACIÓN")

number1 = int(input("Ingrese el primer número: "))
number2 = int(input("Ingrese el segundo número: "))

mult = number1 * number2

print("La multiplicación es: ", mult ,", gracias.")



MULTIPLICACIÓN
La multiplicación es:  35 , gracias.


In [20]:
# 3: Lee una lista de palabras del usuario e imprime la lista en orden inverso.

lista_user = []

contador= 0
while contador < 3:
    palabra = input("ingrese 5 palabras: ")
    lista_user.append(palabra)
    contador += 1
    
lista_user.reverse()
print(lista_user)

['julio', 'rafa', 'fer']


In [3]:
# 4: Pide al usuario ingresar una lista de números y cuenta cuántos son pares e impares.

lista_user_numbers = []
contador = 0
contador_pos = 0
contador_neg = 0

while contador < 5:
    number = int(input("ingrese valor: "))
    lista_user_numbers.append(number)
   
    if number % 2 == 0:
        contador_pos += 1
    else:
        contador_neg += 1

    contador += 1

print("lista = ", lista_user_numbers)

print("positivos: ", contador_pos)
print("negativos: ", contador_neg)


lista =  [4, 4, 4, 4, 5]
positivos:  4
negativos:  1


In [14]:
# 5: Solicita al usuario ingresar una lista de números y calcula el promedio de esos números.

notas_user = []
contador = 0
while contador < 2:
    notas = float(input("Ingrese la nota: "))
    notas_user.append(notas)
    # promedio
    suma_total = sum(notas_user)
    cant_valores = len(notas_user)

    promedio = suma_total / cant_valores

    contador += 1

print("Notas: " , notas_user)
print("El promedio es: " , promedio)

Notas:  [13.0, 17.0]
El promedio es:  15.0


In [ ]:
# 6: Escribe una función que encuentre el valor máximo en una lista y pide al usuario ingresar una lista para probarla.

def max_lista(lista):
    if not lista:
        return None
    else:
        maximo = lista[0]
        for elemento in lista:
            if elemento > maximo:
                maximo = elemento
        return maximo
    
entrada_usuario = input("Ingresa una lista de números separados por espacio: ")
lista_usuario = [int(num) for num in entrada_usuario.split()]

maximo_encontrado = max_lista(lista_usuario)
if maximo_encontrado is not None:
    print(f"El valor máximo en la lista es: {maximo_encontrado}")
else:
    print("La lista está vacía.")

In [28]:
# Ejemplo de usar la función split()

var = "1 2 3 4 5 6 7"
lista_var = [int(num) for num in var.split()]

print(lista_var)

print(lista_var[2:5])

[1, 2, 3, 4, 5, 6, 7]
[3, 4, 5]


In [8]:
# 7: Implementa una función que ordene una lista de números de menor a mayor. Pide al usuario ingresar una lista y luego imprímela ordenada.

def ord_lista(lista):
    lista_ordenada= sorted(lista)
    
    print("lista: ", lista)
    print("lista ordenanda: ",lista_ordenada)

    


lista_user= input("Ingrese una lista de numeros separados por espacios o comas: ")
lista1 = [int(num) for num in lista_user.split()]

ord_lista(lista1)




lista:  [2, 4, 7, 9, 2, 4, 6]
lista ordenanda:  [2, 2, 4, 4, 6, 7, 9]


In [13]:
# 8: Escribe una función que tome una matriz como entrada (usando NumPy) y devuelva su matriz transpuesta.

import numpy as np

def matriz_transpuesta(matriz):
    """
    Toma una matriz como entrada y devuelve su matriz transpuesta.
    
    Parameters:
    matriz (numpy.ndarray): La matriz de entrada.
    
    Returns:
    numpy.ndarray: La matriz transpuesta.
    """
    matriz_transpuesta = np.transpose(matriz)
    # Alternativamente, puedes usar matriz_transpuesta = matriz.T
    
    return matriz_transpuesta

# Ejemplo de uso

matriz1_user= input("ingrese los numeros: ")
matriz1 = [int(num) for num in matriz1_user.split()]

matriz2_user= input("ingrese los numeros: ")
matriz2 = [int(num) for num in matriz2_user.split()]


matriz_entrada = np.array([matriz1, matriz2])
resultado_transpuesta = matriz_transpuesta(matriz_entrada)

print("Matriz de entrada:")
print(matriz_entrada)

print("\nMatriz transpuesta:")
print(resultado_transpuesta)

Matriz de entrada:
[[1 2 3]
 [4 5 6]]

Matriz transpuesta:
[[1 4]
 [2 5]
 [3 6]]


In [14]:
# 10: Pide al usuario ingresar una lista de números y utiliza NumPy para calcular la media y la desviación estándar.

import numpy as np

# Solicitar al usuario ingresar una lista de números
entrada_usuario = input("Ingresa una lista de números separados por espacio: ")
numeros = [float(num) for num in entrada_usuario.split()]

# Convertir la lista a un array NumPy
array_numeros = np.array(numeros)

# Calcular la media y desviación estándar usando NumPy
media = np.mean(array_numeros)
desviacion_estandar = np.std(array_numeros)

# Mostrar los resultados
print(f"La media de la lista es: {media}")
print(f"La desviación estándar de la lista es: {desviacion_estandar}")


La media de la lista es: 4.8
La desviación estándar de la lista es: 2.5612496949731396


In [15]:
# formas de usar arrays numpy:

arr2 = np.zeros((3, 4))

print(arr2) # me da como resultado un array de 3x4 lleno de ceros.

arr1 = np.array([1, 2, 3]) # Crear un array a partir de una lista.

# Multiplicar todos los elementos por 2.
arr = np.array([1, 2, 3])
resultado = arr * 2

# Acceder a elementos individuales, filas o columnas utilizando índices y realizar slicing de la misma manera que en las listas:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

elemento = matriz[1, 2] # Acceder al elemento en la segunda fila y tercer columna.

columna = matriz[:, 0] # Obtener la primera columna.

#  Funciones y métodos para realizar operaciones matriciales y estadísticas en los arrays.
arr = np.array([1, 2, 3, 4, 5])

suma = np.sum(arr) # Calcular la suma de los elementos.

media = np.mean(arr) # Calcular la media.



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
